[phases.setup]
nixPkgs = [
    "python311", 
    "python311Packages.pip",
    "python311Packages.virtualenv"
]

[phases.install]
cmds = [
    "python -m venv .venv",
    "source .venv/bin/activate && pip install --upgrade pip",
    "source .venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "source .venv/bin/activate && python rotenberg_bot.py"
